env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  eqeqeq:
    - error
    - smart
  no-unused-vars: warn
  no-console: [error, { allow: [warn, error] }]
